# FITS Files 

FITS (Flexible Image Transport System) files are used in modern day astronomy all the time.FITS Files are used to store data. Examples of the data stored are in the form of images and tables. 

## Opening a FITS File

The astropy.io.fits.util.get_testdata_filepath() function, used in the examples here, is for accessing data shipped with astropy. To work with your own data instead, please use astropy.io.fits.open(), which takes either the relative or absolute path.

## Opening and Editing Existing Files 

* Firstly, import the fits package from the library astropy.io. 
* Secondly, use the function fits.util.get_testdata_filepath() with the fits filename (of course don't forget te extension .fits) inside the brackets. 
* Lastly, use the fits.open() function to open the FITS file.

In the code below, we import fits from the astropy.io library. We obtain the data from the fits file ," test0.fits". We then store it into the variable ,"fits_image_file". We open the fits file and store the information in the variable , "hdu".The open function will return a list of HDU (Header Data Unit) objects called HDUList. The HDU list is the highest component of the FITS File.

In [82]:
from astropy.io import fits 
fits_image_file = fits.util.get_testdata_filepath('test0.fits')

hdulist = fits.open(fits_image_file)

To obtain information about the HDU List. We use the .info() attribute.

In [83]:
hdulist.info()

Filename: c:\Users\pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\astropy\io\fits\tests\data\test0.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     138   ()      
  1  SCI           1 ImageHDU        61   (40, 40)   int16   
  2  SCI           2 ImageHDU        61   (40, 40)   int16   
  3  SCI           3 ImageHDU        61   (40, 40)   int16   
  4  SCI           4 ImageHDU        61   (40, 40)   int16   


When you are done with the HDU File. Close it with the .close() attribute

In [84]:
hdu.close()

## Working with FITS Headers 

An HDU List consists of an object that has both header and data attributes which are used to access the header and data portions of the data.

In [85]:
from astropy.io import fits 
fits_image_file = fits.util.get_testdata_filepath('test0.fits')

hdulist = fits.open(fits_image_file)

In [86]:
hdulist[0].header['targname']

KeyError: "Keyword 'TARGNAME' not found."

##  Image Data 

The data attribute opperating on image data will return an N-dimensional array (ndarry) object

In [ ]:
print(hdulist[1].data)

[[313 312 313 ... 312 313 313]
 [315 315 313 ... 312 314 313]
 [313 313 312 ... 314 312 313]
 ...
 [314 313 312 ... 312 313 311]
 [313 315 312 ... 313 313 312]
 [312 314 314 ... 314 311 314]]


In the above code, we output the image data of the second HDU object (hdulist[1]). Astropy index starts from 0 and not 1.

hdulist[0] is the first HDU object. 

In [ ]:
data = hdulist["SCI"].data 
print(data)

[[313 312 313 ... 312 313 313]
 [315 315 313 ... 312 314 313]
 [313 313 312 ... 314 312 313]
 ...
 [314 313 312 ... 312 313 311]
 [313 315 312 ... 313 313 312]
 [312 314 314 ... 314 311 314]]


In [ ]:
data0 = hdulist[0].data
print(data0)

None


In [ ]:
datasci2 = hdulist['sci', 2].data
print(datasci2)

[[349 349 348 ... 350 346 348]
 [349 349 347 ... 348 350 348]
 [347 350 349 ... 349 349 349]
 ...
 [349 348 349 ... 348 350 349]
 [349 348 348 ... 348 348 347]
 [348 349 348 ... 348 349 348]]


In [ ]:
datasci2.shape
(40, 40)
datasci2.dtype.name
'int16'

'int16'

In [ ]:
data[30:40, 10:20]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

## Working with Table Data 

We can read and write table data using FITS.

In [ ]:
fits_table_file = fits.util.get_testdata_filepath('tb.fits') #To get the table 
hdul = fits.open(fits_table_file) 
data = hdul[1].data 
hdul.close 

<bound method HDUList.close of [<astropy.io.fits.hdu.image.PrimaryHDU object at 0x0000022056F9C950>, <astropy.io.fits.hdu.table.BinTableHDU object at 0x0000022056F07590>]>

First Row of Table

In [ ]:
print(data[0])

(1, 'abc', 3.7000000715255736, False)


Each and every row is a tuble of various data types be it Boolean, Integer, Sting e.c.t. This is known as a FITS record object. The table has arrays of stored information.

.field() : access tp data column-wise way.

In [ ]:
data.field(1)

chararray(['abc', 'xy'], dtype='<U3')

In [ ]:
data.field(0)

array([1, 2], dtype='>i4')

In [ ]:
data.field(2)

array([3.70000007, 6.69999971])

* .field(0) : acccess the data in the column 1 of the data.
* .field(1) : access the data in the column 2 of the data.
* .field(2) : access the data in the column 3 of the data.

# Column Attributes



.columns gives the information about the columns of the HDU object. 

In [ ]:
fits_table_file = fits.util.get_testdata_filepath('tb.fits')
hdul = fits.open(fits_table_file) 

column_1 = hdul[1].columns
print(column_1)

ColDefs(
    name = 'c1'; format = '1J'; null = -2147483647; disp = 'I11'
    name = 'c2'; format = '3A'; disp = 'A3'
    name = 'c3'; format = '1E'; bscale = 3; bzero = 0.4; disp = 'G15.7'
    name = 'c4'; format = '1L'; disp = 'L6'
)


In [ ]:
column_2 = hdul[1].columns
print(column_2)

ColDefs(
    name = 'c1'; format = '1J'; null = -2147483647; disp = 'I11'
    name = 'c2'; format = '3A'; disp = 'A3'
    name = 'c3'; format = '1E'; bscale = 3; bzero = 0.4; disp = 'G15.7'
    name = 'c4'; format = '1L'; disp = 'L6'
)


ColDefs are short for column definitions. 

# Saving File Changes

HDUList.writeto() : save the changes to fits 

In [ ]:
hdul.writeto('newtable.fits')

# Creating a New FITS File


## Creating a New Image File


So far we have demonstrated how to read and update an existing FITS file. But how about creating a new FITS file from scratch? Such tasks are very convenient in astropy for an image HDU. We will first demonstrate how to create a FITS file consisting of only the primary HDU with image data.

First, we create a numpy object for the data part:



In [88]:
import numpy as np 
n = np.arange(100) # gives float array from 0 to 99

Next, we create a PrimaryHDU object to encapsulate the data:



In [89]:
hdu = fits.PrimaryHDU(n)

We then create an HDUList to contain the newly created primary HDU, and write to a new file:




In [92]:
hdul = fits.HDUList([hdu])
hdul.writeto(('new1.fits'))

OSError: [Errno 22] Invalid argument: 'new1.fits'

In [93]:
hdul = fits.HDUList([hdu])
hdul.writeto('new1.fits')

OSError: [Errno 22] Invalid argument: 'new1.fits'

In [94]:
hdu.writeto('new2.fits')


OSError: [Errno 22] Invalid argument: 'new2.fits'

# Creating a New Table File

If you want to create a binary FITS table with no other HDUs, you can use Table instead and then write to FITS. This is less complicated than “lower-level” FITS interface:

In [95]:
from astropy.table import Table
t = Table([[1, 2], [4, 5], [7, 8]], names=('a', 'b', 'c'))
t.write('table1.fits', format='fits')

OSError: [Errno 22] Invalid argument: 'table1.fits'